import assert from 'node:assert/strict';
import {companionState, companionAction} from '../companions.mjs';
const p={level:1,gold:0,inventory:[]};
assert.equal(companionState(p).unlocked,false);
assert.throws(()=>companionAction(p,'dispatch',1000),/level 2/);
p.level=2;companionAction(p,'dispatch',1000);
assert.throws(()=>companionAction(p,'dispatch',1001),/already/);
assert.throws(()=>companionAction(p,'claim',2000),/not returned/);
const restored=JSON.parse(JSON.stringify(p));
assert.equal(companionState(restored,7201000).ready,true);
restored.inventory=[{id:'potion',qty:20}];
assert.throws(()=>companionAction(restored,'claim',7201000),/Use a tonic/);
assert.ok(restored.companion.expedition);
restored.inventory[0].qty=19;companionAction(restored,'claim',7201000);
assert.equal(restored.gold,12);assert.equal(restored.inventory[0].qty,20);
assert.equal(restored.companion.completed,1);
assert.throws(()=>companionAction(restored,'claim',7201000),/not returned/);
assert.equal(restored.gold,12);
console.log('Companions passed: unlock, server timing, save/reload, capacity and duplicate collection.');
