import assert from 'node:assert/strict';
import {createGuildService} from '../guilds.mjs';
const player=key=>({key,name:key,gold:100,inventory:[],equipment:{},stats:{kills:50},knownDiscoveries:[],activity:{totalFieldActions:0}});
const seller=player('seller'),buyer=player('buyer'),other=player('other');
seller.inventory=[{id:'relic',name:'Glass Blade',power:5,rarity:'Rare'}];
const store=new Map([seller,buyer,other].map(p=>[p.key,structuredClone(p)]));
const service=createGuildService(null,{loadPlayer:key=>structuredClone(store.get(key)),syncPlayer:p=>{store.set(p.key,structuredClone(p));if(p.key===seller.key)Object.assign(seller,p)}});
await service(seller,'list-item',{item:'relic',price:25});assert.equal(seller.inventory.length,0);
const listing=(await service(buyer)).market[0].listing;
const buys=await Promise.allSettled([service(buyer,'buy-item',{listing}),service(other,'buy-item',{listing})]);
assert.equal(buys.filter(r=>r.status==='fulfilled').length,1);
assert.equal(buyer.gold,75);assert.equal(seller.gold,125);assert.equal(other.gold,100);
assert.equal(buyer.inventory.length,1);assert.match(buyer.inventory[0].history[0],/seller to buyer/);
await service(buyer,'list-item',{item:buyer.inventory[0].id,price:30});
await service(buyer,'cancel-listing',{listing:(await service(buyer)).market[0].listing});assert.equal(buyer.inventory.length,1);
await service(seller,'post-contract',{metric:'hunt',target:2,payment:20});assert.equal(seller.gold,105);
const contract=(await service(buyer)).contracts[0].contract;
await service(buyer,'accept-contract',{contract});
await assert.rejects(service(buyer,'claim-contract',{contract}),/new field work/);
await assert.rejects(service(seller,'cancel-contract',{contract}),/unaccepted/);
buyer.stats.kills+=2;await service(buyer,'claim-contract',{contract});assert.equal(buyer.gold,95);
await assert.rejects(service(buyer,'claim-contract',{contract}),/new field work/);
await service(seller,'post-contract',{metric:'field',target:1,payment:10});
const refund=(await service(seller)).contracts[0].contract;
await service(seller,'cancel-contract',{contract:refund});assert.equal(seller.gold,105);
await assert.rejects(service(seller,'cancel-contract',{contract:refund}),/unaccepted/);
await assert.rejects(service(seller,'post-contract',{metric:'hunt',target:1,payment:500}),/funded/);
assert.equal(seller.gold+buyer.gold+other.gold,300);
console.log('Exchange passed: escrow, concurrent single sale, seller credit, cancellation, new-work contracts, refund and currency conservation.');
