import assert from 'node:assert/strict';
import {createArenaService} from '../pvp.mjs';
let clock=1000;
const arena=createArenaService(null,{now:()=>clock});
const player=key=>({key,name:key,origin:'Vanguard',level:2,hp:37,inventory:[],equipment:{}});
const a=player('a'),b=player('b'),c=player('c');
const code=(await arena(a,'create')).match.invitation;
assert.equal((await arena(b)).match,null);
await assert.rejects(arena(a,'join',{code}),/current arena/);
await assert.rejects(arena({...c,level:10},'join',{code}),/three levels/);
await arena(b,'join',{code});
await assert.rejects(arena(c,'move',{move:'attack',revision:1}),/No active duel/);
await assert.rejects(arena(b,'move',{move:'attack',revision:1}),/Wait/);
const moves=await Promise.allSettled([arena(a,'move',{move:'attack',revision:1}),arena(a,'move',{move:'attack',revision:1})]);
assert.equal(moves.filter(r=>r.status==='fulfilled').length,1);
assert.equal((await arena(b)).match.you.hp,88);
await arena(b,'move',{move:'guard',revision:2});
await assert.rejects(arena(a,'move',{move:'attack',revision:1}),/advanced/);
await arena(a,'move',{move:'attack',revision:3});
assert.equal((await arena(b)).match.you.hp,84);
await arena(b,'forfeit');
assert.equal((await arena(a)).record.wins,1);
assert.equal(a.hp,37);assert.equal(b.hp,37);
await assert.rejects(arena(b,'forfeit'),/No active/);
const code2=(await arena(a,'create')).match.invitation;
await arena(b,'join',{code:code2});clock+=45001;
assert.equal((await arena(a)).match.status,'complete');
assert.equal((await arena(b)).record.wins,1);
assert.equal((await arena(b)).record.wins,1); // polling cannot award twice
clock+=600001;
await arena(c,'create');clock+=600001;
assert.equal((await arena(c)).match.status,'cancelled');
await assert.rejects(arena({...c,combat:{}},'create'),/encounter/);
console.log('Live arena passed: two-player consent, brackets, turn/replay protection, concurrent moves, guard, forfeit and timeout.');
