import {spawn,spawnSync} from "node:child_process";
import process from "node:process";
import {readFile} from "node:fs/promises";
const gameSource=await readFile("public/game.js","utf8");
const bindingSource=gameSource.replaceAll("$$(","__ALL__("); if(bindingSource.includes('$("[data-')||gameSource.includes("$$$("))throw new Error("regression: broken selector binding");
if(!gameSource.includes('$=s=>[...document.querySelectorAll(s)]'))throw new Error("multi-selector helper missing");
if(!gameSource.includes("function nearby()")||!gameSource.includes("field-node"))throw new Error("field network UI missing");
if(!gameSource.includes("function traitEffect")||!gameSource.includes("breakbar"))throw new Error("combat depth UI missing");
if(!gameSource.includes("function encounterReveal")||!gameSource.includes("function combatSignature"))throw new Error("encounter/specialization UI missing");
for(const enemy of ["mirehorn","revenant","choirless","riftweaver"])if(!gameSource.includes("function "+enemy+"()"))throw new Error("new enemy art missing: "+enemy);
if(!gameSource.includes("enemyDamage=")||!gameSource.includes("playerDamage="))throw new Error("authoritative combat damage feedback missing");
if(!gameSource.includes('function regionMap()'))throw new Error("regional map renderer missing");
for(const file of ["server.mjs","public/game.js","public/effects.js"]){
 const c=spawnSync(process.execPath,["--check",file],{stdio:"pipe"});
 if(c.status!==0)throw new Error(file+" syntax check failed: "+c.stderr.toString());
}
const port=8791,child=spawn(process.execPath,["server.mjs"],{env:{...process.env,PORT:String(port),DATABASE_URL:""},stdio:["ignore","pipe","pipe"]});
let output="";child.stdout.on("data",d=>output+=d);child.stderr.on("data",d=>output+=d);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{
 for(let i=0;i<40&&!output.includes("listening");i++)await sleep(100);
 if(!output.includes("listening"))throw new Error("server did not start: "+output);
 const base="http://127.0.0.1:"+port;
 const health=await fetch(base+"/health").then(r=>r.json());
 if(!health.ok)throw new Error("health failed");
 for(const asset of ["/","/styles.css","/game.js","/effects.js","/ordinal-icon.svg"]){const r=await fetch(base+asset);if(!r.ok)throw new Error(asset+" not served");}
 const created=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"smoke-player",playerName:"Smoke",origin:"Rogue"})}).then(r=>r.json());
 if(!created.sessionId||created.state.origin!=="Rogue")throw new Error("session create failed");
 const sid=created.sessionId;
 const peer=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"smoke-peer",playerName:"Peer",origin:"Vanguard"})}).then(r=>r.json());
 if(!peer.sessionId)throw new Error("peer session create failed");
 const peerSid=peer.sessionId;
 if(!Array.isArray(created.state.field)||created.state.field.length<4)throw new Error("timed field nodes missing");
 if(!(created.state.ordinalRating>=100))throw new Error("ordinal rating missing");
 if(!created.state.region.objective?.title)throw new Error("shared regional directive missing");
 if(!created.state.region.lastPulseAt)throw new Error("elapsed-time world simulation state missing");
 if(!created.state.regionRule?.label)throw new Error("regional gameplay modifier missing");
 const checkin=await fetch(base+"/api/session/"+sid+"/checkin",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(checkin.state.activity.streak<1)throw new Error("daily sync failed");
 const collectable=checkin.state.field.find(n=>n.action==="collect"&&!n.collected);
 const collected=await fetch(base+"/api/session/"+sid+"/collect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:collectable.id})}).then(r=>r.json());
 if(!collected.state.activity.collected.includes(collectable.id))throw new Error("field collection failed");
 if(!(collected.state.region.objective.progress>=1))throw new Error("regional directive did not receive contribution");
 const peerRefresh=await fetch(base+"/api/session/"+peerSid).then(r=>r.json());
 if(peerRefresh.state.region.objective.progress!==collected.state.region.objective.progress)throw new Error("shared region state did not synchronize across sessions");
 const beforeRace=peerRefresh.state.region.objective.progress;
 const raceA=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"race-a",playerName:"RaceA",origin:"Ranger"})}).then(r=>r.json());
 const raceB=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"race-b",playerName:"RaceB",origin:"Arcanist"})}).then(r=>r.json());
 const raceNode=raceA.state.field.find(n=>n.action==="collect");
 await Promise.all([raceA.sessionId,raceB.sessionId].map(x=>fetch(base+"/api/session/"+x+"/collect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:raceNode.id})}).then(r=>r.json())));
 const raceCheck=await fetch(base+"/api/session/"+sid).then(r=>r.json());
 if(raceCheck.state.region.objective.progress!==beforeRace+2)throw new Error("concurrent regional contributions were lost");
 if(!collected.state.journey?.title||!Array.isArray(collected.state.contractList))throw new Error("personal journey system missing");
 const called=await fetch(base+"/api/session/"+sid+"/calling",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:"hunter"})}).then(r=>r.json());
 if(called.state.journey.calling!=="hunter")throw new Error("calling selection failed");

 const scout=await fetch(base+"/api/session/"+sid+"/scout",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(!(scout.state.region.discoveries||[]).includes("sunken-road"))throw new Error("scouting did not reveal first map landmark");
 if(scout.state.region.discoveryRecords?.["sunken-road"]?.firstDiscoverer!=="Smoke")throw new Error("first-discoverer legacy was not recorded");
 const inv=await fetch(base+"/api/session/"+sid+"/investigate",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(inv.state.combat||!inv.state.pendingEncounter?.modifier?.name||!inv.state.pendingEncounter?.archetype)throw new Error("contact reveal did not stage encounter");
 const engaged=await fetch(base+"/api/session/"+sid+"/engage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choice:"engage"})}).then(r=>r.json());
 if(!engaged.state.combat||engaged.state.pendingEncounter)throw new Error("engagement did not start combat");
 if(!engaged.state.path||engaged.state.path.attack!==0)throw new Error("hidden specialization path missing");
 if(!engaged.state.combat.modifier?.name||!engaged.state.combat.archetype||engaged.state.combat.break!==0)throw new Error("enemy archetype/modifier/Break system missing");
 const failedSkill=await fetch(base+"/api/session/"+sid+"/combat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"skill"})}).then(r=>r.json());
 if(failedSkill.state.combat.turn!==engaged.state.combat.turn||failedSkill.state.combat.flow!==engaged.state.combat.flow||failedSkill.state.combat.lastAction!==engaged.state.combat.lastAction)throw new Error("failed combat action mutated turn state");
 if(failedSkill.state.path.skill!==0)throw new Error("failed combat action trained hidden specialization");
 const hit=await fetch(base+"/api/session/"+sid+"/combat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"attack"})}).then(r=>r.json());
 if(!(hit.state.combat?.hp<engaged.state.combat.hp))throw new Error("combat attack did not deal damage");
 if(hit.state.path.attack!==1)throw new Error("successful combat action did not train hidden specialization");
 if(!(hit.state.mastery?.xp>0))throw new Error("mastery did not progress");
 if(!(hit.state.combat?.break>0))throw new Error("Break gauge did not build");
 if(!hit.state.stats||!hit.state.codex?.enemies)throw new Error("feats/Codex progression missing");
 if(hit.state.combat?.flow!==1)throw new Error("combat Flow did not progress");
 if(!(hit.state.combat?.stamina<100))throw new Error("attack stamina cost missing");
 const withdrew=await fetch(base+"/api/session/"+sid+"/combat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"retreat"})}).then(r=>r.json());
 if(withdrew.state.combat)throw new Error("combat withdrawal failed");
 const roamed=await fetch(base+"/api/session/"+sid+"/roam",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(roamed.state.activity.roams!==1)throw new Error("uncapped Deep Scan loop failed");
 const equipped=await fetch(base+"/api/session/"+sid+"/equip",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:"starter"})}).then(r=>r.json());
 if(equipped.state.equipment.weapon!=="starter")throw new Error("equip route failed");
 console.log("Project Ordinal smoke tests passed");
}finally{child.kill("SIGTERM")}
