import {spawn,spawnSync} from "node:child_process";
import process from "node:process";
import {readFile} from "node:fs/promises";
const gameSource=await readFile("public/game.js","utf8");
const serverSource=await readFile("server.mjs","utf8");
if(!serverSource.includes("function nemesisIdentity")||!serverSource.includes("nemesis?.mutation||profile.modifier"))throw new Error("persistent Nemesis evolution missing");
if(!serverSource.includes("ordinal_meta")||!serverSource.includes("persistenceProbe"))throw new Error("database persistence health marker missing");
if(!serverSource.includes("ordinal_recovery")||!serverSource.includes("function recoveryHash"))throw new Error("hashed cross-device recovery backend missing");
if(!serverSource.includes("function ensureApex")||!serverSource.includes("function apexVictory"))throw new Error("shared Apex Incursion backend missing");
if(!serverSource.includes("function startRift")||!serverSource.includes("function nextRiftWave"))throw new Error("Rift Run backend missing");
if(!serverSource.includes("function makeStoryDecision")||!serverSource.includes("function chooseStoryDecision")||!serverSource.includes('action==="story"'))throw new Error("persistent branching Story Thread backend missing");
if(!serverSource.includes("callingProgressById")||!serverSource.includes("branchBeats"))throw new Error("persistent Calling progress or branch-shaped future beats missing");
if(!gameSource.includes("data-recovery-create")||!gameSource.includes('id="recovery-input"'))throw new Error("cross-device recovery UI missing");
if(/(^|[^$])\$\("\[data-[^"]+\]"\)\.forEach/m.test(gameSource)||gameSource.includes("$"+"$$("))throw new Error("regression: broken collection selector binding");
if(!gameSource.includes('$=s=>[...document.querySelectorAll(s)]'))throw new Error("multi-selector helper missing");
if(!gameSource.includes("function nearby()")||!gameSource.includes("world-contact"))throw new Error("visual Field network UI missing");
if(!gameSource.includes("function traitEffect")||!gameSource.includes("breakbar"))throw new Error("combat depth UI missing");
for(const mapping of ['trait==="Prism Guard"?"shield"','trait==="Veilstep"?"twin"','trait==="Executioner"?"axe"','trait==="Veil-Touched"?"core"'])if(!gameSource.includes(mapping))throw new Error("trait-specific relic art mapping missing: "+mapping);
if(!gameSource.includes("function encounterReveal")||!gameSource.includes("function combatSignature"))throw new Error("encounter/specialization UI missing");
if(!gameSource.includes("story-fracture")||!gameSource.includes("data-story-choice")||!gameSource.includes('act("story"'))throw new Error("browser Story Thread branch UI missing");
if(!gameSource.includes("function fieldInteraction")||!gameSource.includes("data-field-stabilize")||!gameSource.includes("data-field-choice"))throw new Error("Field resonance microinteractions missing");
if(!gameSource.includes("function veilLens")||!gameSource.includes("getUserMedia")||!gameSource.includes("data-lens-pulse")||!gameSource.includes("data-lens-node"))throw new Error("live camera Veil Lens missing");
if(!gameSource.includes("world-stage")||!gameSource.includes("roaming-hostile")||!gameSource.includes("world-player"))throw new Error("living visual Field world missing");
if(!gameSource.includes("function peerAvatar")||!gameSource.includes("world-peer"))throw new Error("live regional Wayfarer projection missing");
if(!gameSource.includes("function rankOverlay")||!gameSource.includes("data-rank-open"))throw new Error("global Ordinal ranking UI missing");
if(!gameSource.includes("FIELD RANGE · F-")||gameSource.includes("distance)+'m")||gameSource.includes("distance+'m"))throw new Error("projected Field range labeling regressed");
if(!gameSource.includes("apex-rift")||!gameSource.includes('data-simple="apex"'))throw new Error("Apex world projection missing");
if(!gameSource.includes("data-combat-arena")||!gameSource.includes('combatGesture("dodge")')||!gameSource.includes('combatGesture("guard")'))throw new Error("gesture-first combat missing");
if(!gameSource.includes("reaction-cue")||!gameSource.includes('label:"SWIPE"')||!gameSource.includes('label:"HOLD"'))throw new Error("visual combat reaction cues missing");
if(!gameSource.includes("gesture-abilities")||!gameSource.includes('await act("roam")'))throw new Error("gesture-primary combat or playable Veil Pulse missing");
if(!gameSource.includes("cameraCombat")||!gameSource.includes("combat-camera-feed")||!gameSource.includes("combat(cameraCombat)"))throw new Error("optional live-camera combat bridge missing");
if(!gameSource.includes("function startFieldMove")||!gameSource.includes("function checkExpeditionProximity")||!gameSource.includes("data-field-stick")||!gameSource.includes("data-expedition"))throw new Error("direct Field exploration controls missing");
if(!gameSource.includes("QUEST DIRECTOR")||!gameSource.includes('data-directive="claim"')||!gameSource.includes('act("directive"'))throw new Error("adaptive Quest Director UI missing");
if(!gameSource.includes("HALL SPECIALTY")||!gameSource.includes('data-guild="promote"')||!gameSource.includes('data-guild="specialize"'))throw new Error("guild officer or specialty controls missing");
if(!gameSource.includes("function armCombatClock")||!gameSource.includes('body:{type:"idle"}')||!gameSource.includes("combat-clock")||!gameSource.includes("if(state?.combat)armCombatClock()"))throw new Error("real-time reaction combat clock missing or does not re-arm");
if(!gameSource.includes("rift-breach")||!gameSource.includes('data-simple="rift"')||!gameSource.includes("RIFT RUN "))throw new Error("Rift Run world activity UI missing");
if(!gameSource.includes("signalPos=signal?fieldCoords(signal):null")||!gameSource.includes("data-world-x=")||!gameSource.includes("signalPos.x"))throw new Error("hostile visual/gameplay coordinates diverged");
for(const enemy of ["mirehorn","revenant","choirless","riftweaver"])if(!gameSource.includes("function "+enemy+"()"))throw new Error("new enemy art missing: "+enemy);
if(!gameSource.includes("enemyDamage=")||!gameSource.includes("playerDamage="))throw new Error("authoritative combat damage feedback missing");
if(!gameSource.includes("travel-paused")||!gameSource.includes("geo(true)"))throw new Error("rapid-travel safety UI/location refresh missing");
if(!gameSource.includes('function regionMap()'))throw new Error("regional map renderer missing");
const effectsSource=await readFile("public/effects.js","utf8");
if(!effectsSource.includes('P.weather==="arc"')||!effectsSource.includes('P.weather==="haze"'))throw new Error("live regional weather renderer missing");
for(const file of ["server.mjs","public/game.js","public/effects.js"]){
 const c=spawnSync(process.execPath,["--check",file],{stdio:"pipe"});
 if(c.status!==0)throw new Error(file+" syntax check failed: "+c.stderr.toString());
}
const port=8791,child=spawn(process.execPath,["server.mjs"],{env:{...process.env,PORT:String(port),DATABASE_URL:""},stdio:["ignore","pipe","pipe"]});
let output="";child.stdout.on("data",d=>output+=d);child.stderr.on("data",d=>output+=d);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{
 for(let i=0;i<40&&!output.includes("listening");i++)await sleep(100);
 if(!output.includes("listening"))throw new Error("server did not start: "+output);
 const base="http://127.0.0.1:"+port;
 const health=await fetch(base+"/health").then(r=>r.json());
 if(!health.ok)throw new Error("health failed");
 if(health.storage!=="memory"||health.databaseConfigured!==false||health.databaseStatus!=="not_configured")throw new Error("database fallback health reporting failed");
 for(const asset of ["/","/styles.css","/game.js","/effects.js","/ordinal-icon.svg","/sw.js"]){const r=await fetch(base+asset);if(!r.ok)throw new Error(asset+" not served");}
 const created=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"smoke-player",playerName:"Smoke",origin:"Rogue"})}).then(r=>r.json());
 if(!created.sessionId||created.state.origin!=="Rogue")throw new Error("session create failed");
 const sid=created.sessionId;
 const firstDirective=created.state.directive;
 if(!firstDirective||!['hunt','discover','field'].includes(firstDirective.kind)||firstDirective.progress!==0)throw new Error("adaptive directive missing");
 const rerouted=await fetch(base+"/api/session/"+sid+"/directive",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choice:"reroute"})}).then(r=>r.json());
 if(rerouted.state.directive.kind===firstDirective.kind||rerouted.state.directive.canReroute!==false)throw new Error("directive reroute did not adapt or enforce daily limit");
 const secondReroute=await fetch(base+"/api/session/"+sid+"/directive",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choice:"reroute"})});
 if(secondReroute.status!==400)throw new Error("second daily directive reroute accepted");
 const earlyClaim=await fetch(base+"/api/session/"+sid+"/directive",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choice:"claim"})});
 if(earlyClaim.status!==400)throw new Error("unfinished directive reward claimed");
 let directed;
 for(let i=0;i<24&&!directed;i++){
  const candidate=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"director-player-"+i,playerName:"Director",origin:"Ranger",lat:10,lon:10})}).then(r=>r.json());
  if(candidate.state.directive.kind==="discover")directed=candidate;
 }
 if(!directed)throw new Error("could not establish discovery directive fixture");
 await fetch(base+"/api/session/"+directed.sessionId+"/scout",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});
 const scouted=await fetch(base+"/api/session/"+directed.sessionId+"/home",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"investigate"})}).then(r=>r.json());
 if(scouted.state.directive.progress!==scouted.state.directive.target)throw new Error("verified discoveries did not advance adaptive directive");
 const directiveGold=scouted.state.gold,directiveRep=scouted.state.reputation,directiveProsperity=scouted.state.region.prosperity,directiveID=scouted.state.directive.id;
 const claimedDirective=await fetch(base+"/api/session/"+directed.sessionId+"/directive",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choice:"claim"})}).then(r=>r.json());
 if(claimedDirective.state.gold!==directiveGold+14||claimedDirective.state.reputation!==directiveRep+2||claimedDirective.state.region.prosperity!==Math.min(100,directiveProsperity+2)||claimedDirective.state.directive.id===directiveID)throw new Error("directive reward, consequence or regeneration failed");
 const recoveryUnavailable=await fetch(base+"/api/recovery/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId:sid})});
 if(recoveryUnavailable.status!==503)throw new Error("recovery endpoint should require persistent storage");
 const recovered=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"smoke-player",recoverOnly:true})}).then(r=>r.json());
 if(!recovered.sessionId||recovered.state.name!=="Smoke")throw new Error("persistent character recovery failed");
 const missingRecovery=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"missing-recovery-player",recoverOnly:true})});
 if(missingRecovery.status!==404)throw new Error("recover-only unexpectedly created a missing character");
 const peer=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"smoke-peer",playerName:"Peer",origin:"Vanguard"})}).then(r=>r.json());
 if(!peer.sessionId)throw new Error("peer session create failed");

 const homeCall=async(action,body)=>{const r=await fetch(base+'/api/session/'+sid+'/'+action,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};};
 const crafted=await homeCall('home',{type:'craft'});
 if(crafted.status!==200||crafted.data.state.gold!==20||crafted.data.state.inventory.find(i=>i.id==='potion').qty!==3)throw Error('home crafting charge or reward failed');
 const helped=await homeCall('keeper',{choice:'help'});
 if(helped.data.state.gold!==10||helped.data.state.home.npc.trust!==1)throw Error('Keeper memory failed');
 if((await homeCall('keeper',{choice:'threaten'})).status!==400)throw Error('repeated Keeper rewards accepted');
 const traced=await homeCall('home',{type:'investigate'});
 if(traced.data.state.home.investigations!==1)throw Error('remote investigation missing');
 if((await homeCall('home',{type:'investigate'})).status!==400)throw Error('remote investigation cooldown bypassed');
 const returned=await fetch(base+'/api/session/'+recovered.sessionId).then(r=>r.json());
 // Existing sessions share character identity; a new recovered session must see saved home memory.
 const homeRecovered=await fetch(base+'/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({playerKey:'smoke-player',recoverOnly:true})}).then(r=>r.json());
 if(homeRecovered.state.home.npc.trust!==1||homeRecovered.state.home.investigations!==1)throw Error('home or NPC persistence failed');
 const peerSid=peer.sessionId;
 const guildCall=async(sessionId,body)=>{
  const r=await fetch(base+'/api/session/'+sessionId+'/guild',body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{});
  return {status:r.status,data:await r.json()};
 };
 const founded=await guildCall(sid,{action:'create',name:'Smoke Guild'});
 if(founded.status!==200||founded.data.guild.role!=='Leader'||!founded.data.guild.invitation)throw Error('guild founding failed');
 const invitation=founded.data.guild.invitation;
 const duplicate=await Promise.all([guildCall(peerSid,{action:'join',code:invitation}),guildCall(peerSid,{action:'join',code:invitation})]);
 if(duplicate.filter(x=>x.status===200).length!==1)throw Error('concurrent duplicate membership accepted');
 const roster=await guildCall(sid);
 if(roster.data.guild.members.length!==2)throw Error('guild roster duplicated');
 const peerGuild=await guildCall(peerSid);
 if(peerGuild.data.guild.invitation!==null||peerGuild.data.guild.members.some(m=>m.member))throw Error('member received leader-only controls');
 if((await guildCall(peerSid,{action:'transfer',member:'smoke-player'})).status!==400)throw Error('member transferred leadership');
 if((await guildCall(sid,{action:'leave'})).status!==400)throw Error('leader abandoned members');
 const successor=roster.data.guild.members.find(m=>m.name==='Peer').member;
 if((await guildCall(sid,{action:'transfer',member:successor})).data.guild.role!=='Member')throw Error('leadership transfer failed');
 if(!(await guildCall(recovered.sessionId)).data.guild)throw Error('guild membership lost across sessions');
 await guildCall(sid,{action:'leave'});
 await guildCall(peerSid,{action:'leave'});
 if((await guildCall(peerSid)).data.guild!==null)throw Error('last-member guild cleanup failed');
 const arenaCall=async(id,input)=>{const response=await fetch(base+'/api/session/'+id+'/pvp',input?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}:{});return {status:response.status,data:await response.json()}};
 const duel=await arenaCall(sid,{action:'create'});
 if(!duel.data.match.invitation)throw Error('live arena invitation missing');
 const blocked=await fetch(base+'/api/session/'+recovered.sessionId+'/home',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'rest'})});
 if(blocked.status!==400)throw Error('second session bypassed arena lock');
 await arenaCall(peerSid,{action:'join',code:duel.data.match.invitation});
 if((await arenaCall(peerSid,{action:'move',move:'attack',revision:1})).status!==400)throw Error('out-of-turn live attack accepted');
 await arenaCall(sid,{action:'move',move:'attack',revision:1});
 if((await arenaCall(peerSid)).data.match.you.hp!==86)throw Error('live arena state not shared');
 await arenaCall(peerSid,{action:'forfeit'});
 if((await arenaCall(sid)).data.record.wins!==1)throw Error('live arena victory missing');
 const offered=await guildCall(peerSid,{action:'create-bounty'});
 if(offered.status!==200||!offered.data.bounties.some(b=>b.own))throw Error('voluntary bounty creation failed');
 const echo=offered.data.bounties.find(b=>b.own).bounty;
 if((await guildCall(peerSid,{action:'hunt-bounty',bounty:echo})).status!==400)throw Error('self bounty accepted');
 if((await guildCall(sid,{action:'claim-bounty'})).status!==400)throw Error('unverified victory claimed');
 const challenge=await guildCall(sid,{action:'hunt-bounty',bounty:echo});
 if(!challenge.data.state.combat?.bountyId)throw Error('Echo arena did not start');
 const beforeEcho=challenge.data.state;
 const echoWithdrawal=await fetch(base+'/api/session/'+sid+'/combat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'retreat'})}).then(r=>r.json());
 if(echoWithdrawal.state.combat||echoWithdrawal.state.hp!==beforeEcho.hp||echoWithdrawal.state.region.threat!==beforeEcho.region.threat)throw Error('arena withdrawal punished the field character');


 const presenceCheck=await fetch(base+"/api/session/"+sid+"/presence").then(r=>r.json());
 if(!presenceCheck.players.some(x=>x.name==="Peer"&&x.rating>=100))throw new Error("live Wayfarer presence rating missing");
 const apexPlayer=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"apex-player",playerName:"ApexTester",origin:"Vanguard"})}).then(r=>r.json());
 const apexFight=await fetch(base+"/api/session/"+apexPlayer.sessionId+"/apex",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(!apexFight.state.combat?.apex||apexFight.state.combat.elite!==2||!apexFight.state.region.apex?.name)throw new Error("shared Apex Incursion failed to start");
 const apexMiss=await fetch(base+"/api/session/"+apexPlayer.sessionId+"/combat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"idle"})}).then(r=>r.json());
 if(!apexMiss.state.combat||apexMiss.state.combat.turn!==apexFight.state.combat.turn+1||!(apexMiss.state.hp<apexFight.state.hp))throw new Error("real-time missed reaction did not resolve an enemy turn");
 const riftPlayer=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"rift-player",playerName:"RiftTester",origin:"Rogue"})}).then(r=>r.json());
 const riftStart=await fetch(base+"/api/session/"+riftPlayer.sessionId+"/rift",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(!riftStart.state.combat?.rift||riftStart.state.combat.riftWave!==1||riftStart.state.riftRun?.total!==3)throw new Error("three-wave Rift Run failed to start");
 const riftExit=await fetch(base+"/api/session/"+riftPlayer.sessionId+"/combat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"retreat"})}).then(r=>r.json());
 if(riftExit.state.combat||riftExit.state.riftRun)throw new Error("Rift Run did not fail cleanly on withdrawal");
 if(!Array.isArray(created.state.field)||created.state.field.length<4)throw new Error("timed field nodes missing");
 if(created.state.field.some(n=>n.distance<90||n.distance>709||n.x<12||n.x>88||n.y<15||n.y>82))throw new Error("Field projection generated invalid unsigned coordinates");
 const leaderboard=await fetch(base+"/api/session/"+sid+"/leaderboard").then(r=>r.json());
 if(!leaderboard.rank||!Array.isArray(leaderboard.leaders)||!leaderboard.leaders.some(x=>x.name==="Smoke"))throw new Error("persistent Ordinal ranking failed");
 if(!(created.state.ordinalRating>=100))throw new Error("ordinal rating missing");
 if(created.state.playBalance?.momentum!==0||created.state.playBalance?.restedCharges!==0)throw new Error("casual/grinder balance state missing");
 if(!created.state.region.objective?.title)throw new Error("shared regional directive missing");
 if(!created.state.region.lastPulseAt)throw new Error("elapsed-time world simulation state missing");
 if(!created.state.regionRule?.label)throw new Error("regional gameplay modifier missing");
 const checkin=await fetch(base+"/api/session/"+sid+"/checkin",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(checkin.state.activity.streak<1)throw new Error("daily sync failed");
 const collectable=checkin.state.field.find(n=>n.action==="collect"&&!n.collected);
 const collected=await fetch(base+"/api/session/"+sid+"/collect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:collectable.id})}).then(r=>r.json());
 if(!collected.state.activity.collected.includes(collectable.id))throw new Error("field collection failed");
 if(!(collected.state.region.objective.progress>=1))throw new Error("regional directive did not receive contribution");
 const peerRefresh=await fetch(base+"/api/session/"+peerSid).then(r=>r.json());
 if(peerRefresh.state.region.objective.progress!==collected.state.region.objective.progress)throw new Error("shared region state did not synchronize across sessions");
 const beforeRace=peerRefresh.state.region.objective.progress;
 const raceA=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"race-a",playerName:"RaceA",origin:"Ranger"})}).then(r=>r.json());
 const raceB=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"race-b",playerName:"RaceB",origin:"Arcanist"})}).then(r=>r.json());
 const raceNode=raceA.state.field.find(n=>n.action==="collect");
 await Promise.all([raceA.sessionId,raceB.sessionId].map(x=>fetch(base+"/api/session/"+x+"/collect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:raceNode.id})}).then(r=>r.json())));
 const raceCheck=await fetch(base+"/api/session/"+sid).then(r=>r.json());
 if(raceCheck.state.region.objective.progress!==beforeRace+2)throw new Error("concurrent regional contributions were lost");
 if(!collected.state.journey?.title||!Array.isArray(collected.state.contractList))throw new Error("personal journey system missing");
 const called=await fetch(base+"/api/session/"+sid+"/calling",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:"hunter"})}).then(r=>r.json());
 if(called.state.journey.calling!=="hunter")throw new Error("calling selection failed");

 const callingPlayer=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"calling-memory-player",playerName:"CallingMemory",origin:"Rogue"})}).then(r=>r.json());
 const seeker=await fetch(base+"/api/session/"+callingPlayer.sessionId+"/calling",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:"seeker"})}).then(r=>r.json());
 const callingNode=seeker.state.field.find(n=>n.action==="collect");
 const seekerProgress=await fetch(base+"/api/session/"+callingPlayer.sessionId+"/collect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:callingNode.id})}).then(r=>r.json());
 if(seekerProgress.state.journey.callingProgress<1)throw new Error("Calling progress did not advance");
 await fetch(base+"/api/session/"+callingPlayer.sessionId+"/calling",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:"hunter"})}).then(r=>r.json());
 const seekerRestored=await fetch(base+"/api/session/"+callingPlayer.sessionId+"/calling",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:"seeker"})}).then(r=>r.json());
 if(seekerRestored.state.journey.callingProgress!==seekerProgress.state.journey.callingProgress)throw new Error("Calling progress was lost after switching away and back");

 const scout=await fetch(base+"/api/session/"+sid+"/scout",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(!(scout.state.region.discoveries||[]).includes("sunken-road")||!(scout.state.knownDiscoveries||[]).includes("sunken-road"))throw new Error("scouting did not reveal personal map landmark");
 if(scout.state.region.discoveryRecords?.["sunken-road"]?.firstDiscoverer!=="Smoke")throw new Error("first-discoverer legacy was not recorded");
 const peerKnowledge=await fetch(base+"/api/session/"+peerSid).then(r=>r.json());
 if((peerKnowledge.state.knownDiscoveries||[]).includes("sunken-road"))throw new Error("shared discovery leaked into another player's personal map");
 const inv=await fetch(base+"/api/session/"+sid+"/investigate",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(inv.state.combat||!inv.state.pendingEncounter?.modifier?.name||!inv.state.pendingEncounter?.archetype)throw new Error("contact reveal did not stage encounter");
 const engaged=await fetch(base+"/api/session/"+sid+"/engage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choice:"engage"})}).then(r=>r.json());
 if(!engaged.state.combat||engaged.state.pendingEncounter)throw new Error("engagement did not start combat");
 if(!engaged.state.path||engaged.state.path.attack!==0)throw new Error("hidden specialization path missing");
 if(!engaged.state.combat.modifier?.name||!engaged.state.combat.archetype||engaged.state.combat.break!==0)throw new Error("enemy archetype/modifier/Break system missing");
 const failedSkill=await fetch(base+"/api/session/"+sid+"/combat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"skill"})}).then(r=>r.json());
 if(failedSkill.state.combat.turn!==engaged.state.combat.turn||failedSkill.state.combat.flow!==engaged.state.combat.flow||failedSkill.state.combat.lastAction!==engaged.state.combat.lastAction)throw new Error("failed combat action mutated turn state");
 if(failedSkill.state.path.skill!==0)throw new Error("failed combat action trained hidden specialization");
 const hit=await fetch(base+"/api/session/"+sid+"/combat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"attack"})}).then(r=>r.json());
 if(!(hit.state.combat?.hp<engaged.state.combat.hp))throw new Error("combat attack did not deal damage");
 if(hit.state.path.attack!==1)throw new Error("successful combat action did not train hidden specialization");
 if(!(hit.state.mastery?.xp>0))throw new Error("mastery did not progress");
 if(!(hit.state.combat?.break>0))throw new Error("Break gauge did not build");
 if(!hit.state.stats||!hit.state.codex?.enemies)throw new Error("feats/Codex progression missing");
 if(hit.state.combat?.flow!==1)throw new Error("combat Flow did not progress");
 if(!(hit.state.combat?.stamina<100))throw new Error("attack stamina cost missing");
 const withdrew=await fetch(base+"/api/session/"+sid+"/combat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"retreat"})}).then(r=>r.json());
 if(withdrew.state.combat)throw new Error("combat withdrawal failed");
 const roamed=await fetch(base+"/api/session/"+sid+"/roam",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json());
 if(roamed.state.activity.roams!==1)throw new Error("uncapped Deep Scan loop failed");
 if(!(roamed.state.playBalance?.momentum>=1))throw new Error("grinder Field Momentum did not advance");
 const equipped=await fetch(base+"/api/session/"+sid+"/equip",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:"starter"})}).then(r=>r.json());
 if(equipped.state.equipment.weapon!=="starter")throw new Error("equip route failed");

 // Reach a real Story Thread fracture entirely through normal gameplay actions.
 const storyPlayer=await fetch(base+"/api/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerKey:"story-branch-player",playerName:"BranchTester",origin:"Ranger"})}).then(r=>r.json());
 let storyState=storyPlayer.state;
 for(const node of storyState.field.filter(n=>n.action==="collect")){
  storyState=(await fetch(base+"/api/session/"+storyPlayer.sessionId+"/collect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:node.id})}).then(r=>r.json())).state;
 }
 storyState=(await fetch(base+"/api/session/"+storyPlayer.sessionId+"/scout",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json())).state;
 storyState=(await fetch(base+"/api/session/"+storyPlayer.sessionId+"/checkin",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json())).state;
 storyState=(await fetch(base+"/api/session/"+storyPlayer.sessionId+"/advance",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json())).state;
 storyState=(await fetch(base+"/api/session/"+storyPlayer.sessionId+"/scout",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}).then(r=>r.json())).state;
 if(storyState.journey.chapter<2||!storyState.storyDecision?.options?.length)throw new Error("normal gameplay did not produce a Story Thread branch");
 const beforeStory={rep:storyState.reputation,gold:storyState.gold,threat:storyState.region.threat,order:storyState.region.order,corruption:storyState.region.corruption};
 const storyChoice=storyState.storyDecision.options[0].id;
 const resolved=(await fetch(base+"/api/session/"+storyPlayer.sessionId+"/story",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({choice:storyChoice})}).then(r=>r.json())).state;
 if(resolved.storyDecision!==null||resolved.journey.choices.length!==1)throw new Error("Story Thread branch did not persist its choice");
 const affinityTotal=Object.values(resolved.journey.affinity).reduce((a,b)=>a+b,0);
 if(affinityTotal!==1)throw new Error("Story Thread affinity did not record the branch");
 if(!resolved.region.history.some(x=>x.includes("altered a hidden Story Thread")))throw new Error("Story Thread branch did not enter shared regional history");
 if(resolved.reputation===beforeStory.rep&&resolved.gold===beforeStory.gold&&resolved.region.threat===beforeStory.threat&&resolved.region.order===beforeStory.order&&resolved.region.corruption===beforeStory.corruption)throw new Error("Story Thread choice had no persistent gameplay consequence");

 console.log("Project Ordinal smoke tests passed");
}finally{child.kill("SIGTERM")}
